all:
	mkdir -p /home/yrimah42/data/elastic_files
	sudo docker-compose up --build

detach:
	mkdir -p /home/yrimah42/data/elastic_files
	sudo docker-compose up --build -d

stop:
	sudo docker-compose stop

down:
	sudo docker-compose down

rm_volume:
	rm -rf /home/yrimah42/data/elastic_files